[package]
name = "com_port_reader"
version = "0.1.0"
edition = "2024"
default-run = "com_port_reader"

[dependencies]
open = "5.4.1"
egui_plot = "0.36.0"
egui_extras = "0.35.0"
chrono = "0.4.44"
crossbeam-channel = "0.5.15"
serialport = "4.9.0"
rfd = "0.17.2"
mlua = {version = "0.12.0", features = ["lua54", "vendored"]}
rusqlite = { version = "0.40.2", features = ["bundled"] }

[dependencies.eframe]
version = "0.35.0"
default-features = false
features = ["accesskit", "default_fonts", "glow"]
