[application]
fps = 20
poll_interval_ms = 1000
max_plot_points_per_series = 1000

[serial]
main_port = "COM3"
emulator_port = "COM4"
baud_rate = 9600
data_bits = 8
parity = "none"
stop_bits = 1
flow_control = "none"
timeout_ms = 250

[emulator]
script_path = 'D:\rust_projects\com_port_reader\emulator_scripts\sine.lua'
