[application]
fps = 10
poll_interval_ms = 5000
max_plot_points_per_series = 1000

[serial]
main_port = "COM10"
emulator_port = "COM11"
baud_rate = 9600
data_bits = 8
parity = "none"
stop_bits = 1
flow_control = "none"
timeout_ms = 250
